version: '3.8'

services:
  # TIER 1 : Entrée (Nginx + Kong)
  reverse-proxy:
    image: nginx:latest
    ports: ["8080:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

  api-gateway:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/opt/kong/kong.yml

  # TIER 2 : App (Simulation K8s)
  erp-app:
    image: nginx:alpine
    volumes:
      - ./app_mock/index.html:/usr/share/nginx/html/index.html

  # TIER 3 : Données (Postgres sécurisé)
  database:
    image: postgres:15
    secrets:
      - db_password
      - db_user
    environment:
      POSTGRES_DB: ckare_erp
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user

  # Outils (SonarQube & Grafana)
  sonarqube:
    image: sonarqube:community
    ports: ["9000:9000"]
    environment:
       - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt